# Copyright Jiaqi Liu
---
name: Guide CI/CD

'on':
  pull_request:
  push:
    branches:
      - master

jobs:
  ci-cd:
    name: Tests documentation build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - run: |
          gem install jekyll
          bundle install
          bundle exec jekyll build
        working-directory: docs
